### ISSUE TITLE
[摘要報告] [S2] 按下"了解更多" 無法帶至該區間的結果頁面

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#100]
![untitled](https://user-images.githubusercontent.com/32997044/35547430-f8a2f46a-0570-11e8-8ca4-760ab3a8d9f6.png)
![untitled](https://user-images.githubusercontent.com/32997044/35547515-60cbc56c-0571-11e8-84fe-12cb69819763.jpg)

**Comment by DrRight** [comment]
已看到呈現結果了。可以也把結果訊息秀上去嗎? Ex:  共 XX 則評論

**Comment by weihsiang-lin** [comment]
Fixed

**Comment by DrRight** [comment]
選擇"上上週"的情況下，按下"了解更多"所帶出來的結果內容與時間不相符

**Comment by weihsiang-lin** [comment]
Fixed.
