### ISSUE TITLE
[Dashboard][S2] 填評邀請在沒有填寫tag情況下，不會顯示分類結果

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#104]
沒有tag的情況下，要顯示文字內容的分類結果。
![default](https://user-images.githubusercontent.com/32997044/35559303-6731f042-05e5-11e8-92b0-addc6450cd07.JPG)

**Comment by weihsiang-lin** [comment]
Per discussion, if without tags then shows summary. Otherwise, tags first.
