### ISSUE TITLE
[月報][S1] 一月份內容數字為空

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#109]
![untitled](https://user-images.githubusercontent.com/32997044/35654505-6a083104-06e5-11e8-8227-0107f4a9814b.png)

**Comment by weihsiang-lin** [comment]
Suggest to keep watching this issue.

**Comment by Jeffchang64** [comment]
已修正摘要報告時間設置為local time。
原本會發生錯誤，是因為摘要報告時間設置為UTC，舉例來說，當2月1日1點，前端要求上一個月資料時，應該是得到1月份資料，但這時後端因摘要報告時間設置為UTC，所以時間是1月31日5點，所以抓上一個月資料會抓到12月。

**Comment by DrRight** [comment]
搶鏡診所之2/5週報未收到

**Comment by DrRight** [comment]
請協助在MVP上線前將此項常見問題也加入 Operation Checklist中，每週與每月各個診所都要確認的項目 (by Cloudwatch)，否則合作診所增加時將會更難主動察覺問題。

**Comment by Jeffchang64** [comment]
會增加在CloudWatch Logs中來確認
