### ISSUE TITLE
[Sign up] [S2] Facebook 認證問題: 認證時使用錯誤帳號導致找不到粉絲頁

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#11]
若客戶有多個FB帳號，且sign up時所登入的帳號並非粉絲團的擁有者帳號，認證完會找不到粉絲頁，這部分需要再構思如何避免此情況發生。
建議:
1. 在認證前，先提醒客戶"請先確認目前瀏覽器所登入的FB帳號為粉絲頁的擁有者"。
2. 若客戶找不到粉絲頁，需要有對應機制，比如可以選擇重新認證。

By Jeff

**Comment by weihsiang-lin** [comment]
1. Add words '請確認目前瀏覽器登入之 Facebook 帳號為診所粉絲頁擁有者' while connect FB.
2. If user doesn't have any FB pages then redirect to signup and shows message.
