### ISSUE TITLE
[填評邀請] [S1] 填完客訴的當下，即時監控出現的時間錯誤

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#114]
填完的當下時間是錯的，要過一會才會更改成對的。

請協助確認改CODE時，各種腳本的cases 的side effect 或有關連性的地方
1. Facebook
2. Google (已知有延遲的 known limitation)
3. 客訴

![untitled](https://user-images.githubusercontent.com/32997044/35739968-40d8aab0-082b-11e8-8662-ce393d0744b3.png)

**Comment by Jeffchang64** [comment]
當時正在改code，所以改完之後，現在create private review的timestamp就是正確的了，已經是錯誤的資料我當時有再做修正，所以會看到原本是錯誤的，後來變成正確的。

**Comment by DrRight** [comment]
了解。但是為了避免改CODE與測是同步造成的誤會造成溝通時間的耗損，我們能先開始進行 test/release的版本分割控管? 避免這個情況再發生?

**Comment by Jeffchang64** [comment]
已做production/demo版本控管。
