### ISSUE TITLE
[客訴追蹤] [S1] 結案的客訴無相關紀錄可以查看

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#120]
查找某則結案的客訴，因為沒有任何追蹤紀錄呈現(即使沒有回覆內容)，會覺得資料未經處理。

需求: 若有分配負責人或是改變狀態時，都要有記錄時間，才能夠了解整個時間演進過程。

![untitled](https://user-images.githubusercontent.com/32997044/35765426-51552a86-08bb-11e8-822d-009ca471afb4.png)

**Comment by DrRight** [comment]
建議如下:
![untitled](https://user-images.githubusercontent.com/32997044/35765549-e0566e78-08bd-11e8-9f83-66322cb8e313.png)

**Comment by DrRight** [comment]
在沒有更改負責人與狀態下，點擊"指定負責人或更新狀態"按鈕，不應該產生一則新的紀錄

**Comment by weihsiang-lin** [comment]
According to the change then shows related information.

**Comment by DrRight** [comment]
1. 歷史紀錄--> 利用FILTER選擇查看結案的客訴資料
2. 系統列出結案的客訴資料後，點選其中一篇查看
3. 查看完之後，選回上一頁
4. 回去時頁面是空的，應該還是要當初選的條件下列的資料(like in step 2)
![untitled](https://user-images.githubusercontent.com/32997044/36341857-8f7945b8-13ec-11e8-867f-be595cc07e84.jpg)

**Comment by weihsiang-lin** [comment]
Final comment is the same issue with #138, fixed.

**Comment by DrRight** [comment]
1. 在"沒有設定負責人但有設定狀態"條件下，沒有更動負責人與狀態，點擊"儲存變更"按鈕，還是會產生一則新的紀錄。
2. 在"沒有設定負責人，沒有設定狀態"下，沒有更動負責人與狀態，點擊"儲存變更"按鈕，會跳出Error message。
![default](https://user-images.githubusercontent.com/32997044/36522739-46cc6f5c-17d9-11e8-9909-0b5275c0fbd2.JPG)

**Comment by weihsiang-lin** [comment]
Fixed.
