### ISSUE TITLE
[摘要報告] [S2] 週報會有不只需要看"上週"的需求

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#121]
Trial feedback: 有時候診所一忙或是院長出國，會變成兩週才開一次會，那我們的系統只能查找上一週的結果會變得不方便。

需求:
1. 查詢的時間區間要能夠帶出上上週的資料
2. 點選週報裡面的了解更多時，上一週的週報要能夠直接帶出上一週的結果，上上週的週報要能夠帶出上上一週的結果(另開視窗，帶出FILTERS 跟內容，FILTER要設定好相對應的時間)。
至於開信的時間點，若是要開上上週之前的週報的話，可直接帶到歷史紀錄查詢的頁面即可。

**Comment by DrRight** [comment]
切換至上上週後，左邊邊欄頁籤focus消失
![default](https://user-images.githubusercontent.com/32997044/36136175-1ccdcad6-10ca-11e8-9fa8-93066b72f707.JPG)

**Comment by weihsiang-lin** [comment]
Fixed.
