### ISSUE TITLE
[UI] [S2] 登入頁面的brand icon 比例與解析度不正確

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#124]
1. 解析度有糊掉
2. 長寬比跟原比例不一樣，造成變型。

![untitled](https://user-images.githubusercontent.com/32997044/35773749-f45e82f8-0952-11e8-8f4c-23493a503432.png)

**Comment by weihsiang-lin** [comment]
Fixed.
