### ISSUE TITLE
[週報與月報email] [S1] 呈現層次與wording調整

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#127]
Feedback:  layout設計尚無法一目了然，可以增加字體與顏色的區分， wording有些看不懂，統計數字不太直覺(上表格的好評數跟下表格好評分類數對應不起來，其實是因為我們定義沒說明清楚)。需有百分比才知道比例大小。

建議: 請同時apply 至週報與月報
![untitled](https://user-images.githubusercontent.com/32997044/35774044-4d99cec8-095c-11e8-91a3-1af7c4d5c24f.jpg)
![untitled-2](https://user-images.githubusercontent.com/32997044/35774045-4e9901b8-095c-11e8-9fb9-9fc7f118436b.jpg)

**Comment by DrRight** [comment]
1. Production 週報的"了解更多"會連結到Demo server
2. 在未登入情況下，點選"了解更多"，登入後，仍然要能開啟對應的頁面資料
3. Production 週報發送的時間錯誤
4. Demo 週報未發

**Comment by weihsiang-lin** [comment]
待驗證 production server

**Comment by weihsiang-lin** [comment]
Production server 看起來一切正常！

**Comment by DrRight** [comment]
1. 趨勢顏色顯示錯誤。
2. 趨勢顏色邏輯統一為: 好評上升綠色，好評下降紅色，負評上升紅色，負評下降綠色。
3. 若數字、星等持平，圖標請改為 - (橫線)， 如 - 0 % ，顏色綠色。

![default](https://user-images.githubusercontent.com/32997044/36709954-c0f8a748-1bb5-11e8-80e9-4329a891bca6.JPG)
![2](https://user-images.githubusercontent.com/32997044/36709972-e82b333a-1bb5-11e8-8f74-bda4031f94d8.JPG)
