### ISSUE TITLE
[UI] [S3] Icon 位置與大小需一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#128]
![untitled](https://user-images.githubusercontent.com/32997044/35775626-5f276664-0984-11e8-82a1-d42dc63da91e.png)

**Comment by DrRight** [comment]
已更新三個圖檔皆為512X512 且圖案幾乎滿版，三個圖的面積有對稱了。
X-Plan\Arts\FE_Use

**Comment by weihsiang-lin** [comment]
Using new image and adjust image size to 32x32.
