### ISSUE TITLE
[UI] [S1] "指定負責人或更新狀態"的按鈕 wording 不好懂，狀態default值也需一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#129]
![untitled](https://user-images.githubusercontent.com/32997044/35775707-f74f075c-0985-11e8-9307-54f132ccdcee.png)

**Comment by DrRight** [comment]
於新增評論時，選擇負責人後，狀態UI 要自動變成處理中。

**Comment by DrRight** [comment]
"指定負責人或更新狀態"鈕，仍需改成"儲存變更"

**Comment by weihsiang-lin** [comment]
Revised.

**Comment by DrRight** [comment]
新增評論在僅指定負責人，但未設定狀態情況下，點選"儲存變更"，會跳出"ERROR!!! Internal Server Error"
![default](https://user-images.githubusercontent.com/32997044/36140094-fa7f8ee0-10da-11e8-83b5-ef3a4a7f709b.JPG)

**Comment by DrRight** [comment]
已確認是由於系統正在修改，導致存取異常。

**Comment by DrRight** [comment]
點"編輯"之後，跳入編輯頁面，這裡的"儲存變更"按鈕wording未修正。
另外，"取消"按鈕沒有作用。
![default](https://user-images.githubusercontent.com/32997044/36147029-929efe52-10f1-11e8-80e7-8f8de8d03a0f.JPG)

**Comment by weihsiang-lin** [comment]
Revise user operation flow of update Facebook reply.

**Comment by DrRight** [comment]
>>於新增評論時，選擇負責人後，狀態UI 要自動變成處理中 
--> 這項還是NG，狀態沒有自動變處理中
![untitled](https://user-images.githubusercontent.com/32997044/36341667-812863b6-13e9-11e8-82e6-283e952a094a.jpg)

**Comment by DrRight** [comment]
編輯reply時，若未修改內容，直接點"更新"，再按"取消"，會跳出錯誤訊息。

![image](https://user-images.githubusercontent.com/32997044/36708465-1736b706-1bae-11e8-9fab-7d38c3a7888b.png)
