### ISSUE TITLE
[UI] [S1] 點擊 "刪除"(評論&人員)，應跳出再確認對話框 

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#134]

**Comment by DrRight** [comment]
增加新的reply後，點"刪除"，不會跳出再確認對話框

**Comment by DrRight** [comment]
目前看起來是只有第一則reply點"刪除"會跳出再確認對話框，之後的reply，都不會跳出再確認對話框，也刪不掉。

**Comment by DrRight** [comment]
在此操作下，選擇"取消"，對話會跳出多次框詢問是否取消。
覆現方式: 
1. 在回覆區域輸入文字
2. 點擊"回覆"
3. 在新reply還未出現時，點另一則reply "編輯"
4. "取消"
5. 此時點"刪除"就會看到此現象

**Comment by weihsiang-lin** [comment]
導入 轉場 #147 效果，因此上述現象將無法重現。
