### ISSUE TITLE
[客訴處理][S1] 變更案件處理狀態後報錯

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#140]
![untitled](https://user-images.githubusercontent.com/32997044/36367279-dd7862f4-1549-11e8-9429-110bc98ba72c.jpg)

如上，狀態更新失敗。

若是再試著更改一次狀態，則就會成功。

**Comment by weihsiang-lin** [comment]
於前端顯示錯誤訊息已追蹤錯誤狀態！

**Comment by weihsiang-lin** [comment]
已修正前端錯誤訊息，KEEP WATCHING this issue.

**Comment by DrRight** [comment]
Please add retry and log

**Comment by weihsiang-lin** [comment]
已加入 retry 機制，log 原先就存在
