### ISSUE TITLE
[使用者權限][S1] two-level user accounts

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#142]
1. 新增 "診所人員" 權限
2. 在認證信中增加診所人員的帳號密碼:
    a. 帳號: staff@clinic_id
    b. 密碼: 亂數8碼 (在設定頁中，管理者可修改staff pw)
3. "診所人員"權限:
    a. 不可回文
    b. 不可編輯評論 and 紀錄
    c. 不可變更密碼
    d. 不可變更人員
    e. 能發送邀請

**Comment by weihsiang-lin** [comment]
可用下列帳號密碼測試

帳號：staff@101
密碼：Abcd1234
