### ISSUE TITLE
[付款金流][S1] 智付通整合註冊流程

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#143]

**Comment by DrRight** [comment]
Ref:https://www.howpin.me/clientterms

**Comment by DrRight** [comment]
帳號設定頁需有合約資訊:
ex:
合約資料
付費方式: 季繳                                                       
合約期間: 107年3月8日 至 107年7月8日
費用: 10,797 元
付費續約(按鈕)       繳費歷史查詢(按鈕)

**Comment by DrRight** [comment]
季繳金額錯誤，應為10,797元
![default](https://user-images.githubusercontent.com/32997044/38552763-cdcce640-3cef-11e8-92c2-bc667cf90c7b.JPG)

**Comment by weihsiang-lin** [comment]
Per discussed, the price is correct.
