### ISSUE TITLE
[S1] 請刪除無用的帳號

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#148]

**Comment by weihsiang-lin** [comment]
寄送日報、週報與月報的條件之一為使用者帳號被啟動。目前已將 demo 機器內的帳號關閉且僅存 ID = 97, 101（我測試使用的帳號）, 105 & 106（其餘帳號已與 @Jeffchang64 哥 sync 過惹）。

**Comment by DrRight** [comment]
請將診所 ID （帳號 ID）= 93 (97) 也關閉，以免影響驗證

**Comment by weihsiang-lin** [comment]
Done
