### ISSUE TITLE
[SignUp] [S1] 無法加入GMB管理者成功 

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#16]
1. 會先叫我輸入Google帳號
2. 同意howpin.me變成管理者
3. 之後就如下圖:

問題1: 我的Google帳號有兩個商家可以管理，那我可以選是要管哪個嗎?
問題2: 欲接管的管理者權限會是? 應該為"MANAGER"?
![untitled](https://user-images.githubusercontent.com/32997044/34459305-aed48462-ee27-11e7-8704-30036f1cf294.jpg)

**Comment by DrRight** [comment]
![issue1](https://user-images.githubusercontent.com/32997044/34758934-1c9104a2-f5d1-11e7-879f-5f3e95a6ed04.jpg)
[GMB_Added_Error.docx](https://github.com/DrRight/Howpin_FE_WebServer/files/1617745/GMB_Added_Error.docx)

**Comment by DrRight** [comment]
1. 加入管理者的是商家地點，非商家帳戶
2. Manager

**Comment by weihsiang-lin** [comment]
已將 PDF 嵌入

**Comment by DrRight** [comment]
請再協助也嵌入PDF於"設定"裡的Google 商家設定功能。

**Comment by weihsiang-lin** [comment]
已嵌入於**設定**裡
