### ISSUE TITLE
[SignUp] [S1] 卡在GMB商家認證頁面，無法再繼續下去

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#17]
無法前進至下一個頁面繼續操作

![untitled](https://user-images.githubusercontent.com/32997044/34459314-041a93d0-ee28-11e7-926b-8cb314c2977a.jpg)

**Comment by weihsiang-lin** [comment]
請參考最新註冊流程！

藉由判斷 locations 來確認使用者新加入的 商家 資料。
