### ISSUE TITLE
[S1] 每日客訴的昨日新增演算法有誤

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#184]
<img width="973" alt="untitled" src="https://user-images.githubusercontent.com/32997044/38350687-017be6cc-38df-11e8-9335-bf17ec91ce0a.png">

**Comment by weihsiang-lin** [comment]
Fixed and phased in production server, let's verify tomorrow.

Root cause: data type comparison (str vs. int).
Solution: Change data type from str to int.
