### ISSUE TITLE
[SignUp] [S1] 尚未完成註冊流程，但EMAIL已被註冊

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#20]
1. 因為發生了一些意外，尚未完成註冊流程，想要再重新註冊。
2. 重新註冊一次，但是到了FACEBOOK綁定那頁，按了連結按鈕，會跳回Sign up的第一頁，並顯示帳號已建立

![untitled](https://user-images.githubusercontent.com/32997044/34511580-b0dd1590-f097-11e7-9591-bb5b3f15816f.png)

**Comment by weihsiang-lin** [comment]
請參考最新註冊流程！
1. 在第一頁會判斷是否重複註冊帳號。
2. 最後一步才將註冊相關資訊寫入前後端資料庫。
