### ISSUE TITLE
[Signup][S1] 按Enter直接跳到Facebook認證頁面

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#21]
在wizard page 1與page 2，在沒有輸入資料的情形下，按鍵盤上Enter key，會直接跳到wizard page 3 Facebook 認證頁面

**Comment by weihsiang-lin** [comment]
增加一段程式碼，阻擋使用者按壓 ENTER 
`$(document).keypress(function(e){`
`    if (e.which == 13){`
`         return false;`
`    }`
`});`
