### ISSUE TITLE
[填評邀請][S2] 選擇"不滿意項目"與填寫更多描述時，縮小頁面，會看到錯誤layout

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#25]
![s_7281063265277](https://user-images.githubusercontent.com/32997044/34705233-fde0e032-f539-11e7-8ed0-3935e594c4db.jpg)
![s_7281071855090](https://user-images.githubusercontent.com/32997044/34705236-09469778-f53a-11e7-8c03-ac13b06340be.jpg)
![s_7281088727236](https://user-images.githubusercontent.com/32997044/34705249-1e1c8680-f53a-11e7-988b-7142551a0cd6.jpg)

**Comment by weihsiang-lin** [comment]
Fixed.
