### ISSUE TITLE
[Signup][S1] Google 商家頁面說明不清與流程卡關

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#30]
![issue](https://user-images.githubusercontent.com/32997044/34757950-85d7367a-f5cc-11e7-9199-48126b35a07e.jpg)

**Comment by weihsiang-lin** [comment]
如果抓不到新增加的 Google 商家，跳回「設定 Google 商家」的頁面並顯示訊息請使用者再次設定！
![2018-01-11 2 48 50](https://user-images.githubusercontent.com/6593821/34811988-ad75fc8a-f6de-11e7-97ea-22942152b943.png)
