### ISSUE TITLE
[即時監控] [S1] 新增 Facebook 評論無法顯示出來

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#38]
Account: howpin2018@gmail.com
Page :  Facebook 搶光牙醫診所
![untitled](https://user-images.githubusercontent.com/32997044/35194137-19a34e16-fea6-11e7-8738-ba56757afecb.png)

**Comment by Jeffchang64** [comment]
1. 因content為None造成無法分析，導致後續流程無法寫入DB內，已修正

**Comment by DrRight** [comment]
[Russell]
我這邊無法進行驗證。
因搶鏡牙醫診所與巧虎牙醫診所的Facebook粉絲團目前已無法公開留言。
請協助使用FACEBOOK沙盒OR其他方式做double confirm.

**Comment by DrRight** [comment]
Tips:
剛研究了一下，發現我們如果要建FACEBOOK帳號來留評，必須先養一下帳號。也就是帳號鋼建完時，留下的評論只能是朋友的朋友才看得到，必須等到該帳號多一點朋友與多一點活動時，才有資格發表公開的評論。
