### ISSUE TITLE
[填評邀請] [S1] 客訴問券輸入文字區域不適當

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#39]
無法看到輸入的字

![1117](https://user-images.githubusercontent.com/32997044/35194204-a3a030b0-fea7-11e7-93fa-fc6e8c99a2d4.jpg)
![20180121_194003](https://user-images.githubusercontent.com/32997044/35194239-33f9ff6a-fea8-11e7-8f93-88c8a4738104.png)

**Comment by DrRight** [comment]
Samsung S7 OK.
Waiting for iPhone's verification results.

**Comment by DrRight** [comment]
iPhone6 plus has improved but not fixed completely.
Defer in Trial and get fixed in next.

**Comment by weihsiang-lin** [comment]
Fix with #146, keep watching this.
