### ISSUE TITLE
[即時監控] [S1] 好評總數與社群上的不一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#40]
![untitled](https://user-images.githubusercontent.com/32997044/35194367-84389958-feaa-11e7-9354-54cb15f93e3c.png)

**Comment by Jeffchang64** [comment]
此為#38延伸問題，因Notification在沒有收到正確回應的情況下會重送，後端在收到notification時，會先將新的評論的rating加入統計(增加評論數量與rating總和)，才會做評論內容處理，但因#38錯誤，導致評論數增加與rating增加，但沒有正確回應FB Notification，所以FB Notification重送，因而造成即時監控數量多於實際數量。

**Comment by DrRight** [comment]
目前看數量還是不一致
![untitled](https://user-images.githubusercontent.com/32997044/36347099-ba3e4a50-1446-11e8-8ed1-39182952e5f8.png)
![untitled](https://user-images.githubusercontent.com/32997044/36347107-ea1e3cc6-1446-11e8-8019-5495090d983d.jpg)

**Comment by Jeffchang64** [comment]
Production Scheduler DB 設定未正確(Demo未改成Production)導致沒有更新Production DB內容。
另外，GMB其實有17則評論，網頁上一則一則去算也可以算出有17則，但網頁上的數字顯示16則。
