### ISSUE TITLE
[即時監控] [S1] 緊急客訴資料錯誤，負責人敘述也空白

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#45]
Account: howpin2018@gmail.com

![untitled](https://user-images.githubusercontent.com/32997044/35314042-7d468d36-00bb-11e8-96a1-991b1c1eea40.png)

**Comment by weihsiang-lin** [comment]
Missing PIC information due to frontend and backend data type difference, fixed.

In addition, the same root cause in issue #59.
