### ISSUE TITLE
[客訴追蹤] [S1] 正評的評價也算進去客訴

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#48]
Account: howpin2018@gmail.com　

![issue](https://user-images.githubusercontent.com/32997044/35314559-d6ed6f96-00be-11e8-99c2-49c717ea6ea7.png)

**Comment by Jeffchang64** [comment]
已修正。
filter結果與數字圖表都只顯示與計算客訴review (rating <3)
