### ISSUE TITLE
[填評邀請][S1] MMS訊息開頭建議改為敘述重點提要

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#5]
由於消費者會先看到簡訊預覽後，才有興趣點擊下去

建議簡訊開頭改成:
感謝蒞臨XX牙醫診所

Device: LG Stylus 2 Dual
Android ver: 6.0.1

![6040](https://user-images.githubusercontent.com/32997044/34412855-a7281896-ec1a-11e7-8aa0-f9b1af6f84a0.jpg)

**Comment by weihsiang-lin** [comment]
![img_2122](https://user-images.githubusercontent.com/6593821/34481650-4c49733e-efee-11e7-8b5e-b41c0fb196cd.PNG)
