### ISSUE TITLE
[客訴追蹤][S2] 統計資料中的曲線圖時間區間錯誤

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#54]
![untitled](https://user-images.githubusercontent.com/32997044/35317947-10885ed4-00d1-11e8-9b35-4b719619e19a.png)

**Comment by weihsiang-lin** [comment]
已調整時間軸，由小到大

**Comment by Jeffchang64** [comment]
因資料定義為"過去六個月"各單位的客訴總數，所以從12月(本月為1月)開始往前6個月是正確的。
