### ISSUE TITLE
[客訴追蹤] [S2] 無使用到的類別出現在UI上

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#56]
![untitled](https://user-images.githubusercontent.com/32997044/35318122-e4f0655e-00d1-11e8-9a43-aa6a660f33bb.png)

**Comment by Jeffchang64** [comment]
男醫生與女醫生這兩個類別在後端分類上有用到，因有許多評論內容會提到男醫生或女醫生，對於分類上有其需求，對於診所端處理問題分析上也有幫助。

**Comment by DrRight** [comment]
OK, 誤以為沒用到，暫先CLOSE。
