### ISSUE TITLE
[摘要報告] [S1] 牙套名稱仍誤植

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#57]
![untitled](https://user-images.githubusercontent.com/32997044/35318344-c5f3a2b4-00d2-11e8-8dec-d5bb44d7719b.png)

**Comment by weihsiang-lin** [comment]
Typo error, fixed.

**Comment by DrRight** [comment]
摘要報告裡的描述仍誤植
![untitled](https://user-images.githubusercontent.com/32997044/35548010-a251fc4c-0574-11e8-9d04-fb26e034a3ec.png)

**Comment by DrRight** [comment]
Duplicated as #99
