### ISSUE TITLE
[緊急客訴][S1] 有分配負責人，但即時監控頁面未顯示

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#59]

**Comment by DrRight** [comment]
![untitled](https://user-images.githubusercontent.com/32997044/35318785-cbb78f74-00d4-11e8-86a3-3dd9c9b0426d.png)

**Comment by weihsiang-lin** [comment]
Because of data type difference. (str vs. int) and fixed.
