### ISSUE TITLE
[好評統計] [S1] 好評統計圖表的時間區間錯誤

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#60]
![untitled](https://user-images.githubusercontent.com/32997044/35319138-6bae797e-00d6-11e8-8077-3c630dfd2a79.png)

**Comment by Jeffchang64** [comment]
所有直方圖類圖表順序應統一為有左至右，由小至大的呈現方式

**Comment by DrRight** [comment]
![untitled](https://user-images.githubusercontent.com/32997044/35427785-63f51434-0263-11e8-8d3e-77f3265318f4.png)
