### ISSUE TITLE
[設定][S2] 社群管理設定流程需修正

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#63]
Per discussion,
1. Facebook setting button default disabled.
2. Google 商家若是當初加入時沒設定，在這邊可以設定。但設定過後，也不能再設定一次。
3. Known issue: 若Signup時有設定Google 商家，這邊沒秀出來

**Comment by weihsiang-lin** [comment]
Known issue: 若Signup時有設定Google 商家，這邊沒秀出來

Root cause: Typo error.
