### ISSUE TITLE
[客訴追蹤] [S2] 客訴追蹤的通知信，按此查看所跳往的內容有誤 

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#64]
這裡應呈現 "未結案的所有issue"
且要有相對應的filter

![untitled](https://user-images.githubusercontent.com/32997044/35320934-7b3fad48-00dd-11e8-8c60-702202208960.png)

**Comment by weihsiang-lin** [comment]
客訴追蹤頁面不包含「結案」的 review，所以由 email 點擊回來的狀態將會是「全部」

**Comment by DrRight** [comment]
那可以改成 "未結案全部" or "未完成全部"嗎?

"全部" 聽起來像是有包括"結案"，容易被誤解...
