### ISSUE TITLE
[量測] [S1] 截取到的評論內容與實際上不一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#67]
Clinic ID= 10
![issue](https://user-images.githubusercontent.com/32997044/35377802-7c96fb26-01a8-11e8-81b7-b95518147b15.png)

**Comment by DrRight** [comment]
Facebook & Google 商家 看起來都有評論內容不一致的問題。

**Comment by Jeffchang64** [comment]
clinic id =10 是明仁牙醫診所-兒童專科，clinic id = 11 是文湖牙醫診所。
