### ISSUE TITLE
[客訴追蹤] 分類項目圖的單位不一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#69]
" 6"  跟 "3" 的長度是一樣的。
顧客會誤解孰多孰少。

![issue](https://user-images.githubusercontent.com/32997044/35378223-f1ea0e44-01a9-11e8-9ede-2778c738a0c2.png)

**Comment by weihsiang-lin** [comment]
取項目最大值作為上限
