### ISSUE TITLE
[填評邀請][S2] 選擇"不了謝謝"後續腳本進行錯誤

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#7]
As title

Device: Samsung S7 Edge
Android ver: 7.0

![70250](https://user-images.githubusercontent.com/32997044/34413194-c521f112-ec1c-11e7-8370-56d1209fd131.jpg)

**Comment by weihsiang-lin** [comment]
Fixed.

**Comment by DrRight** [comment]
請改成
謝謝您的回饋。
我們將持續努力提供更好的醫療品質給您。

**Comment by weihsiang-lin** [comment]
Wording revised.

**Comment by DrRight** [comment]
填過正評後--> 再次點選填評連結 --> 選不滿意 --> 引導到官網
不應該引導到官網.

**Comment by weihsiang-lin** [comment]
已修正對應 wording.
<img width="465" alt="2018-02-14 5 41 31" src="https://user-images.githubusercontent.com/6593821/36197397-932e0bc0-11ae-11e8-91a2-9643e520d1e3.png">
<img width="465" alt="2018-02-14 5 41 48" src="https://user-images.githubusercontent.com/6593821/36197407-99701992-11ae-11e8-8e20-51930058fd8a.png">

**Comment by DrRight** [comment]
1.填評開始
2. 選擇滿意
3. 選擇"不了，謝謝"
4. 不應跳至以下頁面，因為未填評論。
![77497](https://user-images.githubusercontent.com/32997044/36313567-d406525c-1329-11e8-9147-09fd2395f999.jpg)
