### ISSUE TITLE
[填評邀請] [S1] 客訴問卷UI同時顯示前頁(選擇不滿意項目)與後頁(填評頁)

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#72]
在選擇完不滿意項目後，點下一頁，跳出填評頁，但前一個頁面並未消失，而是被蓋在下面。
![s_7367641139104](https://user-images.githubusercontent.com/32997044/35384181-73f8e0ea-01ff-11e8-87f5-fc771e79b841.jpg)

**Comment by weihsiang-lin** [comment]
Side effect, fixed.
