### ISSUE TITLE
[首頁] [S1]  因目前頁面無法自動更新數據，需要有ㄧ個重新整理的按鈕於首頁上

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#83]
1/25: 診所端操作人員 誤以為即時監控自動會更新資料

**Comment by DrRight** [comment]
2/3 trial feedback: 就算你們設計有重新整理的按鈕，能否也通知我方該按重新整理了(EX: facebook's notification)，不然我掛一整天也不太會主動去按重新整理的。

**Comment by weihsiang-lin** [comment]
Auto refresh every 30 mins.
