### ISSUE TITLE
[好評目標] [S1]  已增加的好評，未更新到"加入以來"的累計

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#86]
![untitled](https://user-images.githubusercontent.com/32997044/35465565-e50939c4-02f4-11e8-950f-52817be46b5c.png)

**Comment by Jeffchang64** [comment]
好評數字統計方式改變為直接計算DB內資料，以免造成數字異常。

**Comment by Jeffchang64** [comment]
修正Test plan內的
"加入至今"定義，從"申請加入當時SNS的好評總數 + 至今為止產生的好評數" 改為"加入至今為止產生的好評數"
並修改後端數字的計算公式以符合新的定義。
