### ISSUE TITLE
[評價資料] [S1] Google 的評價時間與實際不一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#87]
我是用修改評價星等與內容，1/27早上七點改，最後卻呈現我是1/26晚上改的
![untitled](https://user-images.githubusercontent.com/32997044/35469226-e6e6267e-0328-11e8-90b9-909194eeb864.png)

**Comment by Jeffchang64** [comment]
timezone issue, 已修正

**Comment by DrRight** [comment]
![untitled](https://user-images.githubusercontent.com/32997044/35483433-d097dcd4-0439-11e8-8953-f7a03189f18e.png)

**Comment by Jeffchang64** [comment]
如Issue #89 
已確認:
FB時間(無論post review or reply)皆為local time。
GMB時間(無論post review or reply)皆+8 hours至local time。
以達到時間軸一至。
因GMB時間顯示模糊，若有錯誤先忽略。
