### ISSUE TITLE
[好評目標] [S1] 好評總數與即時監控的數量不一致

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#88]
![untitled](https://user-images.githubusercontent.com/32997044/35472619-5a4a8a92-036a-11e8-94d0-1f2644624392.png)
![untitled](https://user-images.githubusercontent.com/32997044/35472623-7ada88ca-036a-11e8-892a-eac9f185ec5a.jpg)

**Comment by Jeffchang64** [comment]
看起來問題應該是前端在抓好評目標的好評總數時，抓到自從加入後的好評數，而不是好評總數。

**Comment by weihsiang-lin** [comment]
已修正，用錯 backend API！XD
