### ISSUE TITLE
[評價內容] [S1] 更新 Google 上評論的星等與內容後，我們的系統未能同步更新

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#89]
![untitled](https://user-images.githubusercontent.com/32997044/35477717-ae86c95c-03c1-11e8-8e18-c70aca90c052.png)

**Comment by Jeffchang64** [comment]
原本scheduler在定時更新facebook/GMB的流程會先更新facebook再更新GMB，但因為發生搶鏡牙醫粉絲頁的存取限制問題，而無法繼續做GMB更新。
新的scheduler定時更新流程將FB與GMB判斷獨立，FB or GMB發生錯誤不會互相影響更新動作。

**Comment by DrRight** [comment]
時間還是不對

![untitled](https://user-images.githubusercontent.com/32997044/35483469-50e92dd4-043a-11e8-9b1e-36210e0e6088.png)

**Comment by DrRight** [comment]
請協助以下驗證:

1. Post 一則客訴各於Google and Facebook
2. 分配處理人員與狀態
3. 模擬管理者回覆訊息
4. 模擬更改 Google and facebook 星等與內容變成正評
5. 確認以上時間與內容都為正確
