### ISSUE TITLE
[客訴追蹤] [S1] 無法回覆Facebook評論

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#90]
![untitled](https://user-images.githubusercontent.com/32997044/35479991-5586c0ce-03fc-11e8-81fb-5b013d6f0b0c.png)

**Comment by Jeffchang64** [comment]
搶鏡牙醫診所粉絲頁的API存取量已經被我用爆了，所以暫時無法透過API讀寫。
![default](https://user-images.githubusercontent.com/30223551/35480361-40aa1b56-0447-11e8-8ee2-b641bbd47c1a.JPG)
因昨天晚上8點左右使用超過額度，今天晚上8點~9點之後，應該就會恢復正常。

**Comment by DrRight** [comment]
能否得知 API 每日存取量是?

再者建議若是call function時已達每日存取量，能夠隔天再 retry 嗎? 這樣至少確保發送一定是成功的。

**Comment by Jeffchang64** [comment]
以下是截取自於FB對page rate limiting的說明。
![default](https://user-images.githubusercontent.com/30223551/35492829-281b6678-04ea-11e8-86c2-2fb9acb9a333.JPG)
engaged user應該是指粉絲頁管理者，目前只有我1人，所以24小時內有4800次的API呼叫次數。
按照目前程序，每天會有4次API呼叫(scheduler sync)+診所reply次數的API呼叫。
