### ISSUE TITLE
[好評目標 ] [S1] 尚無偵測點擊簡訊之功能

### ISSUE THREAD

**Issue by DrRight** [DrRight/Howpin_FE_WebServer#95]

**Comment by DrRight** [comment]
1.  點擊過FB OR GOOGLE先不要計入已填過
2. 連結失效條件
(1) 72 hrs
(2) private reviewed done

**Comment by DrRight** [comment]
new rules:
1.  簡訊中的 FB/GMB 連結只要有點擊，"好評目標"中的"點擊"就要打勾。

**Comment by DrRight** [comment]
已經填了GMB回饋，但是沒有偵測到已回覆
帳號:howpin201801@gmail.com on production
![untitled](https://user-images.githubusercontent.com/32997044/37010134-fae5da8a-20e1-11e8-9bf7-748e2ba93cc0.png)

**Comment by weihsiang-lin** [comment]
待 Demo server 測試完畢後將上線至 Production server
